# High quality config
#  https://wiki.archlinux.org/title/Mpv#High_quality_configurations
# https://web.archive.org/web/20260101021046/https://thewiki.moe/tutorials/mpv/
# https://iamscum.wordpress.com/guides/videoplayback-guide/mpv-conf/#deband
# https://kenhv.com/blog/setting-up-mpv
profile=high-quality
# hwdec=auto
deband
# Smoothmotion
interpolation
# tscale=oversample # default
# Force video to lock on the display's refresh rate, and change video and audio
# speed to some degree to ensure synchronous playback - can cause problems
# with some drivers and desktop environments.
video-sync=display-resample

# General options
fullscreen
screenshot-dir="~/Images/Captures d’écran/"

# always downmix surround to stereo
audio-channels=stereo
alang=jpn,ja

# Subtitles
sub-auto=fuzzy
sub=1
sub-file-paths=subs:Subs:sub:Sub:Subtitles:subtitles
## Language Priority
slang=eng,en

# fix for playing live mjpeg stream. https://github.com/mpv-player/mpv/issues/1955#issuecomment-103602222
[extension.mjpg]
demuxer-lavf-probescore=25
cache=no
