#!/hint/bash

if [ "$EUID" -eq 0 ]; then
  pm="apt"
else
  pm="sudo apt"
fi

# privileged operations
alias inst="$pm install"
alias asdep="inst --mark-auto"
alias maj="$pm update && $pm full-upgrade"
alias remove="$pm autoremove"
alias purge="$pm autopurge"
alias clean="$pm autoclean"
# non-privileged operations
alias query="apt search"
alias search="apt list -a --installed"
alias pkginfo="apt show"
alias pql="dpkg -l"
alias whose="dpkg -S"
