#!/hint/bash

## core CLI aliases

# alias completion with sudo (see https://askubuntu.com/a/22043)
if command-exists sudo; then alias sudo='sudo '; fi

alias ls='ls --color=auto'
alias ll='ls -lah --time-style=long-iso -v'
alias l='ls -1A'
alias L='less'
alias grep='grep -i --color=auto'
alias g=grep
alias diff='diff -y --suppress-common-lines'
alias df='df -hT -x devtmpfs -x tmpfs'
alias lsblk='lsblk -o NAME,TYPE,SIZE,LABEL,FSTYPE,MOUNTPOINT'
alias cp='cp --reflink=auto'
alias ipa='ip -c -br a'
alias ipl='ip -c -br l'
alias ipr='ip -c -br r'

if command-exists gdu; then alias ncdu=gdu; fi
if command-exists tree; then alias tree='tree -a -I .git'; fi
if command-exists bat; then alias cat=bat; fi
if command-exists fd; then alias fd='fd --unrestricted'; fi

# editor
if command-exists micro; then alias m='micro'; fi
alias e="$EDITOR"

## systemd

# prefix systemctl alias with sudo depending on whether we are root
if [ "$EUID" -eq 0 ]; then
  alias sctl='systemctl'
  else
  alias sctl='sudo systemctl'
fi
# remap most common systemctl commands to not need to prefix them with sctl
for i in enable disable start stop restart reload status reboot poweroff
    do alias $i="sctl $i"
done
alias jctl='journalctl -o short-iso'
alias uctl='systemctl --user'

if command-exists systemd-nspawn; then
    if [ "$EUID" -eq 0 ]; then
        alias nspawn="systemd-nspawn"
    else
        alias nspawn="sudo systemd-nspawn"
    fi
fi

## SSH

if command-exists ssh; then
  alias ssh-forget='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
  alias scp-forget='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
  alias ssh-password='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
  alias ssh-old='ssh -o PubkeyAcceptedAlgorithms=+ssh-rsa -o HostkeyAlgorithms=+ssh-rsa'
fi

## rsync

if command-exists rsync; then
  if [ "$EUID" -eq 0 ]; then
    alias rsync-perfect="rsync -aHAXShUU --info=progress2 --partial"
  else
    alias rsync-perfect="sudo rsync -aHAXShUU --info=progress2 --partial"
  fi
  alias rsync-perfect-remote-sudo="rsync-perfect --rsync-path='sudo rsync'"
fi

## git

if command-exists git; then
  alias gss='git status'
  alias gc='git commit'
  alias gp='git push'
  alias gpu="git pull"
  alias glog='git log --decorate --pretty=oneline --abbrev-commit'
  alias grog='glog --graph'
  alias gdif='git diff'
  # alias gdiff=gdif
fi

if command-exists lazygit; then alias lg='lazygit'; fi

## ffmpeg
if command-exists ffmpeg; then alias ffmpeg='ffmpeg -hide_banner'; fi

## youtube-dl

# make sure any program still calling youtube-dl gets redirected
if command-exists yt-dlp; then
  alias youtube-dl='yt-dlp'
  # common options that I always want
  alias ytdl='yt-dlp --no-mtime --embed-metadata --no-embed-info-json --embed-thumbnail --concurrent-fragments 5 --merge-output-format "mkv" -o "%(uploader)s - %(upload_date)s - %(title)s.%(ext)s"'
  # parallel downloading
  if command-exists aria2c; then
    alias ytdlx='ytdl --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M"'
  fi
  # download music
  alias ytdlm='ytdl -f "258/251/22/256/140/250/18/249/139" -o "%(title)s.%(ext)s"'
  # alter: --format "(bestaudio[acodec^=opus]/bestaudio)/best"

  # "will only choose combinations that fit either WebM (VP8/VP9+Vorbis/Opus) or MP4 (H.264+AAC)"
  alias ytdlv='ytdl -f "bestvideo[ext=webm]+251/bestvideo[ext=mp4]+(258/256/140)/bestvideo[ext=webm]+(250/249)/best"'
  # old -f bestvideo\[height\<\=\?1080\]\+bestaudio\/best

  # archiving
  # see https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/scripts/Archivist%20Scripts/Archivist%20Scripts%20(No%20Comments)/Unique/Unique.sh
  # and https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f#yt-dlp-usage-example
  alias ytdl-archive='ytdl --no-overwrites --parse-metadata "%(title)s:%(meta_title)s" --parse-metadata "%(uploader)s:%(meta_artist)s"'
  alias ytdl-archive-desc='ytdl-archive --write-description'
  alias ytdl-archive-sub='ytdl-archive --write-sub --sub-format "srt/ass/best" --sub-lang en,fr --embed-subs'
  alias ytdl-archive-all='ytdl-archive --write-sub --sub-format "srt/ass/best" --sub-lang en,fr --embed-subs --write-description --write-info-json --write-annotations --write-thumbnail'
fi

## phoronix-test-suite
if command-exists phoronix-test-suite; then alias pts="phoronix-test-suite"; fi

## Terraform
if command-exists terraform; then alias tf='terraform'; fi

## Docker
if command-exists docker; then
    alias d='docker'
    alias dps='docker ps'
    alias dpsa='docker ps -a'
    alias dc='docker compose'
fi

## Incus
if command-exists incus; then
    alias i='incus'
    alias ils='i ls --columns ns4ts'
    function incus-docker-rebuild {
      for i in $@ ; do
          i rebuild docker:$(incus config show $i | awk '/image.id/ {print $2}') $i -f --debug
          i start $i
      done
    }
    function incus-gh-rebuild {
      for i in $@ ; do
          i rebuild ghcr:$(incus config show $i | awk '/image.id/ {print $2}') $i -f --debug
          i start $i
      done
    }
fi

## Oracle Cloud
if command-exists uv; then
    alias oci='uvx --from oci-cli oci'
fi
