#!/hint/bash

## ffmpeg

if command-exists ffmpeg; then alias ffmpeg='ffmpeg -hide_banner'; fi

## youtube-dl

# make sure any program still calling youtube-dl gets redirected
if command-exists yt-dlp; then
  alias youtube-dl='yt-dlp'
  # common options that I always want
  alias ytdl='yt-dlp --no-mtime --embed-metadata --no-embed-info-json --embed-thumbnail --concurrent-fragments 5 --merge-output-format "mkv" -o "%(uploader)s - %(upload_date)s - %(title)s.%(ext)s"'
  # parallel downloading
  if command-exists aria2c; then
    alias ytdlx='ytdl --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M"'
  fi
  # download music
  alias ytdlm='ytdl -f "258/251/22/256/140/250/18/249/139" -o "%(title)s.%(ext)s"'
  # alter: --format "(bestaudio[acodec^=opus]/bestaudio)/best"

  # "will only choose combinations that fit either WebM (VP8/VP9+Vorbis/Opus) or MP4 (H.264+AAC)"
  alias ytdlv='ytdl -f "bestvideo[ext=webm]+251/bestvideo[ext=mp4]+(258/256/140)/bestvideo[ext=webm]+(250/249)/best"'
  # old -f bestvideo\[height\<\=\?1080\]\+bestaudio\/best

  # archiving
  # see https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/scripts/Archivist%20Scripts/Archivist%20Scripts%20(No%20Comments)/Unique/Unique.sh
  # and https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f#yt-dlp-usage-example
  alias ytdl-archive='ytdl --no-overwrites --parse-metadata "%(title)s:%(meta_title)s" --parse-metadata "%(uploader)s:%(meta_artist)s"'
  alias ytdl-archive-desc='ytdl-archive --write-description'
  alias ytdl-archive-sub='ytdl-archive --write-sub --sub-format "srt/ass/best" --sub-lang en,fr --embed-subs'
  alias ytdl-archive-all='ytdl-archive --write-sub --sub-format "srt/ass/best" --sub-lang en,fr --embed-subs --write-description --write-info-json --write-annotations --write-thumbnail'
fi

## phoronix-test-suite

if command-exists phoronix-test-suite; then alias pts="phoronix-test-suite"; fi

## Terraform

if command-exists terraform; then  alias tf='terraform'; fi

