directory: ~/Musique/collection
plugins: convert duplicates fromfilename chroma
per_disc_numbering: yes
ui:
    color: yes

import:
#    move: yes
    log: ~/.config/beets/import.log
paths:
    multidisc: $albumartist/$year - $album%aunique{}/$disc.$track - $title

