directory: ~/Musique/collection
plugins: convert duplicates fromfilename chroma inline

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''

import:
    copy: no
    incremental: yes
    log: ~/.config/beets/import.log


per_disc_numbering: yes
item_fields:
# from plugin example:
#    initial: albumartist[0].upper() + u'.'
#    disc_and_track: u'%02i-%02i' % (disc, track) if
#                    disctotal > 1 else u'%02i' % (track)
# from FAQ:
    multidisc: 1 if disctotal > 1 else 0

paths:
    default: $albumartist/%if{$year,($year) }$album%aunique{}/%if{$multidisc,$disc-}$track. $title
    comp: $album%aunique{}%if{$year, ($year)}/%if{$multidisc,$disc-}$track. $artist - $title
    singleton: $artist/$title
